### ISSUE TITLE
Feature request: please, remove `ilovebieber` or make it optional

### ISSUE THREAD

**Issue by Flashwalker** [clbr/fifth#24]
Сan you please remove `ilovebieber` annoying prompt or make it optional?

**Comment by clbr** [comment]
It is a core security feature. It cannot be runtime configurable, because then malware could disable it without you knowing any better (plenty of such examples in Firefox).

A compile-time config option could certainly be added, if you're happy with an insecure browser; patches welcome. I would certainly not trust it with banking, etc. then.

**Comment by clbr** [comment]
Oh, if you'd like to disable it for your own build only, comment the wk_set_ssl* calls in main.cpp.

**Comment by Flashwalker** [comment]
Thanks
